### ISSUE TITLE
HS300 (`TPLinkSmartMultiPlug`) smartdevice.SetPoweredOn() can only run once.

### ISSUE THREAD

**Issue by doggy8088** [CodeBardian/tplink-smartdevices-netstandard#20]
Here is my code:

```cs
async Task Main()
{
    var discoveredDevices = await new TPLinkDiscovery().Discover(timeout: 1500, target: "192.168.33.255");
    if (discoveredDevices.Count == 0) { return; }
    foreach (TPLinkSmartMultiPlug smartdevice in discoveredDevices)
    {
        for (int i = 0; i < smartdevice.OutletCount; i++)
        {
            var outlet = smartdevice.Outlets[i];
            if (!outlet.OutletPowered)
            {
                await smartdevice.SetPoweredOn(true, outletId: i);
            }
            else
            {
                await smartdevice.SetPoweredOn(false, outletId: i);
            }
        }
    }
}
```

Only the first Outlet is able to turn on/off successfully. The second one will get the following error: `Value cannot be null. (Parameter 'propertyName')`

Here is the stack trace:

![image](https://user-images.githubusercontent.com/88981/181074285-317d599d-e96c-4796-b8bd-6afa0966b56f.png)

**Comment by CodeBardian** [comment]
This exact issue (`Value cannot be null. (Parameter 'propertyName')` using `setPoweredOn` on multiplugs) was fixed by #18. I assume you installed through nuget where I didn't publish this yet. I will take care of that in a couple of days.

In the meantime you could clone the repo, build the .dll yourself and then reference the .dll in your project. Otherwise wait some days until I get some time to update the nuget.
