### ISSUE TITLE
var Smartplug gives null value

### ISSUE THREAD

**Issue by GameDeveloper2017** [CodeBardian/tplink-smartdevices-netstandard#7]
I have my HS105 mini smart plug connected to the same internet as my laptop and I have the line:
I got rid of await from the discovery line and got this error:
                    var smartPlug = new TPLinkSmartPlug("100.10.4.1"); but I am getting a null value

any fix? this happens during the execution

Edit: when I add the await and make my method an async void, I get this error: System.Net.Sockets.SocketException: 'Only one usage of each socket address (protocol/network address/port) is normally permitted' on this line:  var discoveredDevices = await new TPLinkDiscovery().Discover();

**Comment by CodeBardian** [comment]
Confirm that you are using latest version 1.0.3 ? Because that error from your edit has already come up some time ago (#1).
Did you change the argument of constructor to the ip-address of your plug?  

At the time I can't look into that as I won't be home for the next couple weeks. In the meantime it would be helpful if you could provide more information on the error itself (e.g. stacktrace) and your .net  platform and version so that I can  possibly reproduce the issue. Thanks.

**Comment by GameDeveloper2017** [comment]
How to I find the IP address of my plug?

**Comment by GameDeveloper2017** [comment]
I got the IP address Everything works perfectly! Quick Question, how would I make a GUI that's like the Kasa app that can discover these devices?

**Comment by CodeBardian** [comment]
For a desktop application read up on using Windows Forms or WPF. Xamarin could be used for a mobile application on  android/ios if you want to make an app like Kasa itself.
